sudo: required
dist: trusty

language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
  allow_failures:
    - jdk: openjdk11

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: true
script: ./gradlew build

notifications:
  email: false
